library(devtools)
original_wd <- getwd()
setwd("data-raw")
estratorim_arte_OAB <- read.csv("estratorim_arte_OAB.csv", colClasses=c("factor", "factor", "factor"))
save(estratorim_arte_OAB, file = "estratorim_arte_OAB.RData")
setwd(original_wd)
rm(original_wd, estratorim_arte_OAB)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
