library(devtools)
original_wd <- getwd()
setwd("data-raw")
puerto <- read.csv("puerto.csv", colClasses = c("factor", "factor"))
save(puerto, file = "puerto.RData")
setwd(original_wd)
rm(original_wd, puerto)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
