library(devtools)
original_wd <- getwd()
setwd("data-raw")
especies_no_mezcla <- read.csv("especies_no_mezcla.csv")
save(especies_no_mezcla, file = "especies_no_mezcla.RData")
setwd(original_wd)
rm(original_wd, especies_no_mezcla)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
