library(devtools)
original_wd <- getwd()
setwd("data-raw")
origen <- read.csv("origen.csv", colClasses = c("factor", "factor"))
save(origen, file = "origen.RData")
setwd(original_wd)
rm(original_wd, origen)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
