library(devtools)
original_wd <- getwd()
setwd("data-raw")
cfpo2017 <- read.csv("cfpo2017.csv", sep = ";")
save(cfpo2017, file = "cfpo2017.RData")
setwd(original_wd)
rm(original_wd, cfpo2017)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
