library(devtools)
original_wd <- getwd()
setwd("data-raw")
maestro_flota_sireno <- read.csv("maestro_flota_sireno.csv", sep = ";")
maestro_flota_sireno$BARCOD <- sprintf("%06d", maestro_flota_sireno$BARCOD)
save(maestro_flota_sireno, file = "maestro_flota_sireno.RData")
setwd(original_wd)
rm(original_wd, maestro_flota_sireno)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
