library(devtools)
original_wd <- getwd()
setwd("data-raw")
especies_mezcla <- read.csv("especies_mezcla.csv")
save(especies_mezcla, file = "especies_mezcla.RData")
setwd(original_wd)
rm(original_wd, especies_mezcla)
devtools::use_data_raw()
# IMPORTANT: COPY FILE TO /data
# AND THEN: devtools::use_data()
