# ---- function to import the 'tallas por up' files ----------------------------
#' Import OAB reports from SIRENO.
#'
#' This function import the OAB report files from SIRENO: hauls, trips, catches,
#' lengths, litter and accidental files.
#'
#' @note The SIRENO catches report must be generated with the option 'by
#' category'. The SIRENO hauls report must be generated with the
#' option 'only hauls'. The SIRENO Lengths report must be generated by categories.
#' @param mareas vector with the names of the haul files
#' @param lances vector with the names of the trip files
#' @param capturas vector with the names of the catch filenames
#' @param tallas vector with the names of the length filenames
#' @param basuras vector with the names of the litter filenames
#' @param accidentales vector the names of the accidental filenames
#' @param path path of the files. The working directory by default.
#' @param export to export muestreos_up dataframe in csv file. False by default.
#' @return Return a list with 6 data frames
#' @export

importOABFiles <- function(mareas, lances, capturas, tallas, basuras,
                           accidentales, export = FALSE, path = getwd()){

  # I DON'T KNOW WHAT IS IT: DELETE???
  # check mareas, lances, capturas and tallas has the same number of rows
  # elements <- list(mareas, lances, capturas, tallas, basuras, accidentales)
  # number_of_elements <- lapply(elements, nrow)
  # if(length(unique(number_of_elements)) != 1){
  #   stop(paste0("the variables", mareas, ", ", lances, ", ", capturas, ",", tallas, ",", basuras, ",", accidentales, "does not have the same length."))
  # }

  # import files
  trips <- importOABTrips(mareas, path)
  hauls <- importOABHauls(lances, path)
  catches <- importOABCatches(capturas, path)
  lengths <- importOABLengths(tallas, path)
  litter <- importOABLitter(basuras, path)
  accidentals <- importOABAccidentals(accidentales, path)

  # group in a list
  samples_oab<-list(hauls=hauls, trips=trips, catches=catches, lengths=lengths,
                    litter=litter, accidentals=accidentals)

  # filter by month, only in case by_month == TRUE
  # by_month <- check_by_month_argument(by_month)
  #
  # if (by_month != FALSE){
  #   muestreos_up <- lapply(muestreos_up, function(x){x <- filter_by_month(x, by_month); x})
  # }

  if (isTRUE(export)){
    exportListToCsv(samples_oab)
  }

  #return list
  return(samples_oab)
}
